### PR TITLE
Unified interface

### PR DESCRIPTION
**Pull request by BoBiene**
based on #20 

**I tried to prevent any breaking changes**

- added IMetrics interface
- added ISparkplugConnection
- added SparkplugBaseOptions
- added TLS options
- added option to disable 
    - AddSessionNumberToCommandMessages 
    - AddSessionNumberToDataMessages
- added Async Event-Pattern
- added more events 
    - Application
        - DeviceBirthReceived
        - DeviceDeathReceived
        - NodeBirthReceived
        - NodeDeathReceived
- added  SparkplugTopic & SparkplugMessageTopic class
- use IEnumerable for Metrics instead of List in parameters
- added KnownMetricStorage
    - possiblity for clients to change the behavior when the metric is not in the Known-Metric list

### CODE REVIEW

**Comment by SeppPenner** [comment]
This will take a bit longer to verify, but seems to be a good idea.

**Comment by BoBiene** [comment]
I've found some issues and will fix them the next days.

**Comment by SeppPenner** [comment]
> I've found some issues and will fix them the next days.

No problem, I haven't looked at it yet and will be on vacation for some days either ;)

**Comment by BoBiene** [comment]
@SeppPenner so hopefully this is all. It will go throug our QA department as part of our usage so there will maybe follow some fixes. But the generall work is done from my side. Looking forward to receice your feedback.

**Comment by BoBiene** [comment]
@SeppPenner did you already find some time to look at this?

**Comment by SeppPenner** [comment]
> @SeppPenner did you already find some time to look at this?

Not yet, but I will check it right now :)

**Comment by SeppPenner** [comment]
@all-contributors please add @BoBiene for code test

**Comment by SeppPenner** [comment]
I have merged your pull request and checked it. Looks very good (I just adjusted some code style things mainly).

 I still need to verify your question on Gitter (Where the events should occur-Node or application) and need to check the async events (and probably should run some tests with the new code) :)

**Pull request merged**
