### PR TITLE
adds integration tests, debug output json, minor bug fix

### PR DESCRIPTION
**Pull request by faldeland**

### CODE REVIEW

**Comment by faldeland** [comment]
Not sure which test(s) are failing. Assumed the integration tests. Attempted to set Ignore flag for integration tests. Still shows "1 test has failed"

**Comment by faldeland** [comment]
Here were some of the errors I was getting before your latest commit. With the minor bug fix, the integration tests are now working as I think they should.
errors

**Comment by SeppPenner** [comment]
I have some questions:

1. Are you sure that we need the changes made in line SparkplugNodeBase.cs, line 359, 428 and 439? --> Ah ok, I understand it now what your aim was. Looks good :)
2. Why do we again need the different data type enums? (`SparkplugADataType` and `SparkplugBDataType`).

**Comment by faldeland** [comment]
> I have some questions:
> 
> 1. Are you sure that we need the changes made in line SparkplugNodeBase.cs, line 359, 428 and 439? --> Ah ok, I understand it now what your aim was. Looks good :)
> 2. Why do we again need the different data type enums? (`SparkplugADataType` and `SparkplugBDataType`).

All changes are a direct result of testing against Sparkplug compliant Server/Primary Application.
The spec is a little "off" in regards to section numbers...but here is the section that calls it out.
image

Here is the section that enumerates what the DataType enum value is and what the corresponding Protobuf enum value is.
image

**Comment by SeppPenner** [comment]
Ah, I see. I will need to change this in the next days, I guess ;D

**Comment by SeppPenner** [comment]
With the two different enum representations, we need as well two different payload definitions and and two different metric definitions (The internal ProtoBuf ones and the externally used ones). Makes it a bit more complicated, i guess :D

**Comment by SeppPenner** [comment]
Now, there is an update containing the conversion between the different models (internal and external) in code.

**Pull request merged**
