### PR TITLE
Bugfix/signed numeric types

### PR DESCRIPTION
**Pull request by TimJoehnk**
Changes for better consistency with unsigned and signed numeric types
-  IntValues are now of type int
- LongValues are now of type long
- Added new Properties ULongValue and UIntValue
- DateTime Values are now mapped to new ULongValue Property instead to LongValue
- Updated all type switched according to changes
- SessionSequenceNumber is set to ULongValue aswell
- Added Unit Test checking for negative signed values

### CODE REVIEW

**Comment by TimJoehnk** [comment]
@SeppPenner Hi, can you please review this PR when you have a chance?

**Comment by SeppPenner** [comment]
Hi, thank you for the contribution. I hope to get this whole project to version 3.0 compatibility soon and will check this PR within the step.

**Comment by Patrick2607** [comment]
@TimJoehnk Have you looked at the Sparkplug B specification? Although I understand your changes, this request does not conform to the specification (found [here](https://sparkplug.eclipse.org/specification/version/2.2/documents/sparkplug-specification-2.2.pdf)). Specifically page 44 where it defines what Metrics exist with their corresponding int value:

```javascript
oneof value {
  uint32 int_value = 10;
  uint64 long_value = 11;
  float float_value = 12;
  double double_value = 13;
  bool boolean_value = 14;
  string string_value = 15;
  bytes bytes_value = 16;
  DataSet dataset_value = 17;
  Template template_value = 18;
  MetricValueExtension extension_value = 19;
}
```

**Comment by malessainray** [comment]
It seems like the specification is missing details regarding converting numeric values for transport layer encoding. There is an open discussion here: https://github.com/eclipse-sparkplug/sparkplug/issues/453

**Comment by TimJoehnk** [comment]
> @TimJoehnk Have you looked at the Sparkplug B specification? Although I understand your changes, this request does not conform to the specification (found [here](https://sparkplug.eclipse.org/specification/version/2.2/documents/sparkplug-specification-2.2.pdf)). Specifically page 44 where it defines what Metrics exist with their corresponding int value:
> 
> ```cs
> oneof value {
>   uint32 int_value = 10;
>   uint64 long_value = 11;
>   float float_value = 12;
>   double double_value = 13;
>   bool boolean_value = 14;
>   string string_value = 15;
>   bytes bytes_value = 16;
>   DataSet dataset_value = 17;
>   Template template_value = 18;
>   MetricValueExtension extension_value = 19;
> }
> ```

Yes, you are right. Signed integers should be encoded as unsigned integers.

**Comment by SeppPenner** [comment]
I wasn't sure about this either. Also I believe that the change is technically correct, Sparkplug V3 lacks a bit of specification in this case. Maybe v4 will fix this. I would keep the PR open just as a "reminder" to check this again later.

**Comment by SeppPenner** [comment]
I have added the missing data types in 1.3.0+. I guess, until Sparkplug version 4 there is nothing we can do here... @TimJoehnk Still thank you for your contribution.

**Pull request closed without merging**
